version: "3"
services: 
  mongo:
    container_name: kuloko_mongo
    image: mongo
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_DATABASE=local
    # environment:
    #     MONGO_INITDB_ROOT_USERNAME: admin
    #     MONGO_INITDB_ROOT_PASSWORD: pw
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
      - ${HOST_BASE_DIR}/geco_commons/mongodb/init/:/docker-entrypoint-initdb.d
    env_file:
      .env
    command: --auth
    networks:
      shared-nw:
        ipv4_address: 172.30.0.1
    privileged: true
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  mongo-express:
    container_name: kuloko_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    env_file:
      .env
    networks:
      shared-nw:
        ipv4_address: 172.30.0.2
    depends_on:
      - mongo
      
  kuloko_python:
    container_name: kuloko_python
    build:
      context: .
      dockerfile: kuloko_dockerfile
    volumes:
      - ${HOST_BASE_DIR}/kuloko:/root/src/kuloko
      - ${HOST_BASE_DIR}/geco_commons:/root/src/geco_commons
    working_dir: ${BASE_DIR}
    environment:
      HOME: ${KULOKO_DIR}
    env_file:
      .env
    restart: always
    tty: true

    networks:
      shared-nw:
        ipv4_address: 172.30.0.3

networks:
    default:
      external:
          name: bridge
    # Connection  among conntianers
    shared-nw:
      external: true

secrets:
  MONGO_INITDB_ROOT_USERNAME:
    file: ${HOST_BASE_DIR}/geco_commons/mongodb/secret/.MONGO_INITDB_ROOT_USERNAME
  MONGO_INITDB_ROOT_PASSWORD:
    file: ${HOST_BASE_DIR}/geco_commons/mongodb/secret/.MONGO_INITDB_ROOT_PASSWORD
