version: "3"
services:
  mongo:
    container_name: kuloko_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27018:27018
    volumes:
      - ${HOST_DATA_BASE_DIR}/kuloko_db:/data/db
      - ./configdb:/data/configdb
      - ${HOST_BASE_DIR}/geco_commons/mongodb/init/:/docker-entrypoint-initdb.d:ro
    env_file: .env
    command: mongod --port 27018 --auth
    networks:
      shared-nw:
        ipv4_address: 172.30.0.1
    # privileged: true
    secrets:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27018/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    container_name: kuloko_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: kuloko_mongo
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_pw
    env_file: .env
    networks:
      shared-nw:
        ipv4_address: 172.30.0.2
    depends_on:
      mongo:
        condition: service_healthy

  kuloko_python:
    container_name: kuloko_python
    build:
      context: .
      dockerfile: kuloko_dockerfile
    volumes:
      - ${HOST_BASE_DIR}/kuloko:/root/src/kuloko
      - ${HOST_BASE_DIR}/geco_commons:/root/src/geco_commons
    working_dir: ${BASE_DIR}
    environment:
      HOME: ${KULOKO_DIR}
    env_file: .env
    restart: always
    ports:
      - 9898:9898
    expose:
      - 9898
    command: jupyter lab --allow-root --ip=0.0.0.0 --port=9898 --no-browser --NotebookApp.token=''
    tty: true
    networks:
      shared-nw:
        ipv4_address: 172.30.0.3

networks:
  default:
    external:
      name: bridge
  # Connection  among conntianers
  shared-nw:
    external: true

secrets:
  MONGO_INITDB_ROOT_USERNAME:
    file: ${HOST_BASE_DIR}/geco_commons/mongodb/secret/MONGO_INITDB_ROOT_USERNAME
  MONGO_INITDB_ROOT_PASSWORD:
    file: ${HOST_BASE_DIR}/geco_commons/mongodb/secret/MONGO_INITDB_ROOT_PASSWORD
