version: "3"
services:  
  kuloko_python:
    container_name: kuloko_python
    build:
      context: .
      dockerfile: kuloko_dockerfile
    volumes:
      - ${BASE_DIR}:/root/src
    working_dir: ${BASE_DIR}
    environment:
      HOME: ${KULOKO_DIR}
    restart: always
    tty: true