AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kuloko_aws

  Sample SAM Template for kuloko_aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3000

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  FeedAgentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: feed_handler/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /feed
            Method: get

  FeedHandlerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: FeedHandlerLayer
      ContentUri: 'function/kuloko_handler.zip'
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7

  tableMyAppUser: 
    Type: "AWS::DynamoDB::Table"
    Properties: 
    # table name
    TableName: Quote

    # 請求モード
    BillingMode: PROVISIONED  
    
    # Attribute
    AttributeDefinitions: 
      - 
        AttributeName: feed_datetime
        AttributeType: S
      - 
        AttributeName: sym
        AttributeType: S

    KeySchema:
      - 
        AttributeName: sym
        KeyType": HASH
      -   
        AttributeName": feed_datetime
        KeyType: RANGE

    # キャパシティユニット( BillingMode が PROVISIONED の場合は必須 )
    ProvisionedThroughput:
      ReadCapacityUnits: 5   # 読み込みキャパシティユニット
      WriteCapacityUnits: 5  # 書き込みキャパシティユニット

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
